---
version: 2
updates:
  -
    package-ecosystem: "github-actions"
    target-branch: develop
    directory: /
    labels:
      - "dependabot"
      - "github-actions"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "docker"
    target-branch: develop
    directory: /
    labels:
      - "dependabot"
      - "docker"
    schedule:
      interval: "daily"
  -
    package-ecosystem: "npm"
    target-branch: develop
    directory: /
    labels:
      - "dependabot"
      - "dependencies"
    schedule:
      interval: "daily"

