---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-service.fullname" . }}
  labels:
    {{- include "backend-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: frontend
      protocol: TCP
      name: frontend
    - port: {{ .Values.service.backend.port }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    {{- include "backend-service.selectorLabels" . | nindent 4 }}
